tpie::sysinfo Struct Reference
tpie::sysinfo Struct Reference
Class providing system and platform info.
#include <tpie/sysinfo.h>
Public Member Functions
sysinfo ()
Default constructor.
std::string commit () const
Git commit hash.
std::string refspec () const
Git refspec.
std::string platform () const
Platform description.
std::string hostname () const
System hostname as reported by Boost ASIO.
std::string blocksize () const
Block size used by tpie::ami::stream.
std::string localtime () const
Local date and time in a human-readable format.
template<typename V >
std::string custominfo (std::string key, const V &value)
Helper function to make a custom key-value line.
template<typename V >
void printinfo (std::string key, const V &value)
Print custom info to std::cout.
Static Public Member Functions
static memory_size_type blocksize_bytes ()
Detailed Description
Class providing system and platform info.
Definition at line 48 of file sysinfo.h.
Constructor & Destructor Documentation
sysinfo()
tpie::sysinfo::sysinfo () inline
Default constructor.
Definition at line 52 of file sysinfo.h.
         : m_platform(calc_platform())
         , m_hostname(calc_hostname())
         , m_blocksize(calc_blocksize())
     {
         // Does nothing.
     }
Member Function Documentation
blocksize()
std::string tpie::sysinfo::blocksize () const inline
Block size used by tpie::ami::stream.
Definition at line 87 of file sysinfo.h.
 { return m_blocksize; }
Referenced by tpie::operator<<().
commit()
std::string tpie::sysinfo::commit () const inline
Git commit hash.
See also
tpie::git_commit
Definition at line 64 of file sysinfo.h.
 { return git_commit; }
References tpie::git_commit.
Referenced by tpie::operator<<().
custominfo()
template<typename V > std::string tpie::sysinfo::custominfo (std::string key, const V & value) inline
Helper function to make a custom key-value line.
sysinfo i;
std::cout << i;
std::cout << i.custominfo("Verbosity", m_verbose ? "On" : "Off")
          << std::endl
          << i.custominfo("", "Starting test") << std::endl;
could print out
"Hostname:       sanford"
"Platform:       Linux 64-bit"
"Git branch:     refs/heads/master"
"Git commit:     5f0bebba1f4b2b53f4bb4d5709d3d347bc469dc9"
"Local time:     2012-Mar-13 11:17:33"
"Block size:     2048 KiB"
"Verbosity:      On"
"                Starting test"
Parameters
key Text to display in left column. Should be at most 14 characters.
value Text to display in right column. Should be at most 63 characters.
Definition at line 123 of file sysinfo.h.
{
         std::stringstream builder;
         if (key != "") key += ':';
         builder.flags(std::ios::left);
         builder << std::setw(16) << key << value;
         return builder.str();
     }
Referenced by printinfo().
hostname()
std::string tpie::sysinfo::hostname () const inline
System hostname as reported by Boost ASIO.
Definition at line 82 of file sysinfo.h.
 { return m_hostname; }
Referenced by tpie::operator<<().
localtime()
std::string tpie::sysinfo::localtime () const inline
Local date and time in a human-readable format.
Definition at line 92 of file sysinfo.h.
{
         boost::posix_time::ptime now = boost::posix_time::second_clock::local_time();
         return to_simple_string(now);
     }
Referenced by tpie::operator<<().
platform()
std::string tpie::sysinfo::platform () const inline
Platform description.
Currently "Windows" or "Linux" followed by "32-bit" or "64-bit" depending on the WIN32 compile-time define and sizeof(size_t).
Definition at line 77 of file sysinfo.h.
 { return m_platform; }
Referenced by tpie::operator<<().
printinfo()
template<typename V > void tpie::sysinfo::printinfo (std::string key, const V & value) inline
Print custom info to std::cout.
Definition at line 135 of file sysinfo.h.
{
         std::cout << custominfo(key, value) << std::endl;
     }
References custominfo().
refspec()
std::string tpie::sysinfo::refspec () const inline
Git refspec.
See also
tpie::git_refspec
Definition at line 70 of file sysinfo.h.
 { return git_refspec; }
References tpie::git_refspec.
Referenced by tpie::operator<<().
The documentation for this struct was generated from the following file:
sysinfo.h